### ISSUE TITLE
Warning: block_featuredcourses returns true in has_config() but does not provide a settings.php file

### ISSUE THREAD

**Issue by leac** [danielneis/moodle-block_featuredcourses#3]
Hi

I get this warning in a Moodle environment I'm developing. I assume I can fix it so has_config() returns fase, but I was wondering of there's something I'm missing.

**Comment by danielneis** [comment]
Hi,

thank you for reporting.
This is fixed on master now. It really does not have a settings.php file =)

**Comment by danielneis** [comment]
Hi,

thank you for reporting.
This is fixed on master now. It really does not have a settings.php file =)
