### ISSUE TITLE
How to make the block have the ability to be added wherever a user wants

### ISSUE THREAD

**Issue by leac** [danielneis/moodle-block_featuredcourses#4]
This isn't an issue, really, it's just a question I've got regarding this block:
The way the block currently works, it can only be added either on the homepage or on the whole site.
I would like to fork this block and change it to behave like other blocks, so it can be added anywhere on the site (for example, I need it on the category page but not in course pages).

In this I need your help, if you may: I couldn't find where in the code it's defined to act that way, and therefore I don't know what I have to change. Could you please direct me?

**Comment by danielneis** [comment]
Hello,

I just made the needed changes to allow the block to be added anywhere. If you download the latest version from git, you will be able to add the block to any page.
There is a link to the commit above.

Best regards,
Daniel
